packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': true
  msgpackr-extract: true
  esbuild: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - 'msgpackr-extract'
  - 'esbuild'
  - 'sharp'
  - 'unrs-resolver'
